[package]
name = "db-context"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false  # TODO: figure out a better name for this crate before enabling publishing: https://github.com/molybdenumsoftware/pr-tracker/issues/1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.1.6"
futures = "0.3.29"
sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio"] }
tempfile = "3.8.1"
fragile-child = { version = "1.0.0", path = "../fragile-child" }
