[dependencies]
camino.workspace = true
confique.workspace = true
serde.workspace = true

[package]
name = "pr-tracker-api-config"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
